### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by michielbdejong** [leibovic/alwaysreader#2]
Using Firefox 44.0.2 on CyanogenMod 12.1-20151227-NIGHTLY-z3c (Android 5.1.1), I get this error when trying to install this addon from https://people.mozilla.org/~mleibovic/alwaysreader.xpi:

> The add-on downloaded from people.mozilla.org could not be installed because it appears to be corrupt.

Any suggestions?

**Comment by leibovic** [comment]
Sorry about that, I think something must have been wrong with the XPI I posted. I just updated it, does it work for you now?

**Comment by michielbdejong** [comment]
Yes, awesome!! I want this on Desktop as well :)
